### ISSUE TITLE
poliagoncharenko / Lab-8

### ISSUE THREAD

**Issue by ananasn** [ITMOPython-2022/Lab-8#1]
@poliagoncharenko
1. Исправить путь до файла в первом задании, или положить файл в нужное место
![Снимок экрана от 2024-04-06 16-18-17](https://github.com/ITMOPython-2022/Lab-8/assets/8919470/775cadc0-14f6-4c4a-bf34-0d7a577debe1)

**Comment by artur20043001** [comment]
это точно мне?

Сб, 6 апр. 2024 г. в 16:19, Anastasiia Krylova ***@***.***>:

**Comment by ananasn** [comment]
Это общий репозиторий, замечание для пользователя @poliagoncharenko
